### ISSUE TITLE
Upgrade Nodes sometimes fails with "Internal Error"

### ISSUE THREAD

**Issue by unchris** [plynx-team/plynx#41]
I've attached a screenshot of the error below:

![error](https://user-images.githubusercontent.com/32913178/81330818-a955db80-906e-11ea-890f-2ec467cbdbec.png)

I don't know what triggers this problem but I'd say close to 50% of the time Upgrade Nodes has this problem and then I have to drag in all the new Operations and set their parameters and links to other Operations again

**Comment by khaxis** [comment]
I've seen it before. Can you see traceback in terminal?

**Comment by khaxis** [comment]
Never mind, it will be resolved in 1.2.0

**Comment by khaxis** [comment]
now should be fixed
